### ISSUE TITLE
KoBERT 사전 학습 데이터

### ISSUE THREAD

**Issue by wonhyukjang** [sktelecom/sktelecom.github.io#107]
안녕하세요,
위키피디아나 뉴스 등에서 사전학습 데이터를 수집 하셨다고 페이지에 써있는데 한국어 위키피디아(https://ko.wikipedia.org/) 에서 수집하신 것이 맞을까요? 
https://sktelecom.github.io/project/kobert/

**Comment by haksungjang** [comment]
안녕하세요! 

KoBERT에 대해서는 여기에 문의 부탁 드립니다. : 
https://github.com/SKTBrain/KoBERT

감사합니다.
