### ISSUE TITLE
KoGPT2

### ISSUE THREAD

**Issue by whygo1004** [sktelecom/sktelecom.github.io#39]
https://github.com/SKT-AI/KoGPT2 에서 KoGPT2 가 공개돼 있다고 하는데 접속하면 없는 페이지로 나옵니다.
KoGPT2를 다운로드할 수 있을까요?

**Comment by justinjoy** [comment]
> KoGPT2

글쎄요? 저도 처음 보는거라 링크가 사라졌다면 더이상 유지보수 하지 않는 프로젝트가 아닐까요?

https://sktelecom.github.io/about/contact/

여기에 문의해보면 어떨까요?

**Comment by haksungjang** [comment]
안녕하세요, 
https://github.com/SKT-AI 측에 확인해보니, KoGPT2의 일부 보완을 위해 잠시 닫은 상태이며, 조만간 오픈할 예정이라고 합니다. 참고하시기 바랍니다. 
감사합니다.

**Comment by whygo1004** [comment]
> 안녕하세요,
> https://github.com/SKT-AI 측에 확인해보니, KoGPT2의 일부 보완을 위해 잠시 닫은 상태이며, 조만간 오픈할 예정이라고 합니다. 참고하시기 바랍니다.
> 감사합니다.

그렇군요. 알려주셔서 감사합니다.
