### ISSUE TITLE
sktelecom.github.io에 있는 card-deck의 반응성 개선

### ISSUE THREAD

**Issue by hyungmogu** [sktelecom/sktelecom.github.io#45]
안녕하세요.

SK텔레콤 오픈소스 포털 [sktelecom.github.io](http://sktelecom.github.io/)에 기여를 하고 싶어 이 이슈를 올립니다.

[sktelecom.github.io](http://sktelecom.github.io/) "Open source projects" section 아래에 있는 card들이 minimum window width: 575px부터 1행 3열로 되어 있다는 것을 봤었습니다.

이 width에서는 spacing이 너무 좁아 콘텐츠가 squeeze되어 보입니다.

이 부분을 display: grid를 사용해서 card들이 minimum window width: 767px이 되면 1행 2열 그리고 minimum window width: 991px이 되면 1행 3열로 되도록 개선을 했습니다.

개선 전:

https://user-images.githubusercontent.com/6856382/162985770-26278ee6-7d1c-411d-81a1-575aefc17ec5.mov

개선 후:

https://user-images.githubusercontent.com/6856382/162985944-bf2deade-efdb-492d-9bda-77505575afd2.mov

display: grid는 전 세계 브라우져의 93%에서 support를 하고 있습니다.

사파리에서는 grid-template-rows에서 버그가 있다고 나와있지만 이 change에서는 grid-template-rows를 사용하고 있지 않습니다.

![Screen Shot 2022-04-12 at 7 59 48 AM](https://user-images.githubusercontent.com/6856382/162986221-80d8bc4b-2605-4c1d-866e-d2cc48cbd4f6.png)

이 change에 display: grid를 사용해도 되는지 확인 부탁드립니다.

제 issue를 봐 주셔서 감사합니다.

**Comment by haksungjang** [comment]
안녕하세요, @hyungmogu 님, SKT 오픈소스 포털에 관심 갖고 기여해주셔서 감사합니다. 
@hyungmogu 님의 기여가 웹사이트의 look&feel에 큰 도움이 되었습니다. 

보내주신 PR은 merge하였습니다. 

앞으로도 많은 관심과 기여 부탁 드립니다. 
감사합니다~ :)

**Comment by hyungmogu** [comment]
정말 고맙습니다! :)
