### ISSUE TITLE
더 이상 사용되지 않는 google_news 메타 테그 제거

### ISSUE THREAD

**Issue by hyungmogu** [sktelecom/sktelecom.github.io#47]
안녕하세요.

sktelecom.github.io clone을 하고 프로잭트 폴더로 들어가 `hugo server`를 실행 했는데 다음의 error가 떴습니다.

```
WARN 2022/04/15 12:05:32 The google_news internal template will be removed in a future release. Please remove calls to this template. See https://github.com/gohugoio/hugo/issues/9172 for additional information.
```

Warning 메세지 속 첨부되어 있는 Github issue 링크([링크1](https://github.com/gohugoio/hugo/issues/9172), [링크2](https://www.seroundtable.com/google-news-meta-keywords-tag-no-longer-supported-25270.html))로 들어가보니 `google_news` 메타 테그가 휴고 그리고 구글에서도 사용되고 있지 않고 있다고 나와 있습니다.

![163627138-0e30282b-5017-4f8c-aef6-c1ea4acbaabe](https://user-images.githubusercontent.com/6856382/163632480-5d46aab3-a934-47a5-b30c-e411eb2f2238.png)

![163626069-54852719-3a12-4118-b244-ac1d125889e5](https://user-images.githubusercontent.com/6856382/163632489-59389397-e147-41f6-8388-a88b174d60da.png)

관리자님, `sktelecom.github.io/layouts/partials/head.html`에 있는 `google_news` 메타 테그를 지워도 괜찮겠습니까?

지우면은 이 warning이 terminal에 안나옵니다.

시간을 내어 제 issue를 봐주셔서 고맙습니다.

감사합니다.

**Comment by haksungjang** [comment]
Merge하였습니다. 

@hyungmogu  님, 감사합니다. :)
