### ISSUE TITLE
sktelecom.github.io 깨진 아이콘

### ISSUE THREAD

**Issue by hyungmogu** [sktelecom/sktelecom.github.io#51]
안녕하세요.

sktelecom.github.io에 있는 깨진 아이콘들을 보며 이 issue를 올립니다.

![icons missing](https://user-images.githubusercontent.com/6856382/164129664-3fcc88fc-01ea-4f66-972c-667bce5c3886.png)

sktelecom.github.io를 clone 해서 hyungmogu.github.io로 다시 올린 다음 두 개의 repository를 비교하니, gh-pages branch에 있는 webfonts 폴더가 missing 합니다.

**hyungmogu.github.io gh-pages:**

![gh-pages-hyungmogu-github-io](https://user-images.githubusercontent.com/6856382/164129754-aca3a479-24e8-484a-862f-9dc8cd923111.png)

![hyungmogu-github-io](https://user-images.githubusercontent.com/6856382/164129764-b6b4714b-a621-46ad-93ee-3ac07db6e625.png)

**sktelecom.github.io gh-pages:**

![gh-pages-sktelecom-github-io](https://user-images.githubusercontent.com/6856382/164129799-5feee25c-25cb-4fd2-a669-6707093f0f77.png)

![sktelecom-github-io](https://user-images.githubusercontent.com/6856382/164129812-a99bc42b-7bef-4af2-90b5-bbdb55106eac.png)

이 폴더를 지우면은 문제를 replicate 할 수 있습니다 ([참고](https://hyungmogu.github.io/)).

![gh-pages hyungmogu-github-io-problem-replicated](https://user-images.githubusercontent.com/6856382/164129837-6e71bd9a-fa1d-41dd-918a-c5aa722bece0.png)

![hyungmogu-github-io-problem-replicated](https://user-images.githubusercontent.com/6856382/164129841-6c9415e8-175b-4b91-8d5c-5d97c53ae9b8.png)

관리자님, github action에서 latest deployment build하는데 webfonts folder가 missing 한데 혹시 회사에서 아이콘을 바꾸실 계획이 있으십니까? 만약 없으시면, 다시 build 하면 원레 상태로 되돌릴 수 있습니다.

![github-actions-comparison](https://user-images.githubusercontent.com/6856382/164129953-7af6165f-c170-4de6-a1ff-85de9016fd37.png)

관리자님, 제 issue를 읽어 주셔서 고맙습니다.

감사합니다.

**Comment by hyungmogu** [comment]
관리자님, 

물론입니다! 

관리자님, 제게 메세지를 주셔서 정말 고맙습니다.

**Comment by haksungjang** [comment]
@hyungmogu 님, 

의견주신대로 다시 build하여 webfont를 복구하였습니다. 
덕분에 이슈 확인 및 대응을 할 수 있었습니다. 

Thank you, again!  :)

**Comment by hyungmogu** [comment]
관리자님, 고맙습니다
