### ISSUE TITLE
sktelecom.github.io의 header 개선

### ISSUE THREAD

**Issue by hyungmogu** [sktelecom/sktelecom.github.io#52]
안녕하세요 관리자님, 

sktelecom.github.io header 개선 관련 issue를 올립니다.

브라우저를 특정 width로 줄이면은 header menu의 부분은 사라졌고 로고가 off position이 됩니다.

![image](https://user-images.githubusercontent.com/6856382/165416189-79135e09-a6bb-47bd-b528-846bf3751822.png)

이것을 보며 “한번 도전해 보자!” 하며 header를 개선했습니다.

-------------------------

첫번째로 모바일 메뉴를 만들었습니다.

디자인은 SK telecom 회사 웹사이트하고 비슷하게 만들었습니다. 사람들에게 "이것은 SK telecom 관련 회사입니다" 인상을 주고 싶었습니다.

https://user-images.githubusercontent.com/72232928/165224860-febf0e45-1262-4966-b62b-50f52f0aaabe.mov

![image](https://user-images.githubusercontent.com/6856382/165416217-eef69256-df08-4d78-a724-50980f03db89.png)

-------------------------

두 번째로 sub menu feature를 추가했습니다

현재의 header는 언어선택 창 빼고는 sub menu 기능이 없습니다. 개선안에서는 3단계까지 sub menu를 추가할 수 있게 하였습니다.

https://user-images.githubusercontent.com/72232928/165224959-3d326941-0566-4e3a-88bf-a6d3ae0bc4a0.mov

-------------------------

세 번째로 장애인들을 위한 접근성을 추가했습니다.

버튼에 aria-label를 넣어 이것이 for open menu인지 for close menu인지 알 수 있게 했습니다.

https://user-images.githubusercontent.com/72232928/165225251-b8f4a648-2b48-4329-b287-4df3efd05cb5.mov

그다음 main menu에서 tab을 계속 누르다 보면 자동으로 sub menu가 열리게 하였습니다.  (shift + tab을 누르면 반대 방향으로 갑니다.)

https://user-images.githubusercontent.com/72232928/165307619-35b03477-2096-4cfc-8693-b4fee0b9bfce.mov

그다음 aria-expanded 그리고 aria-haspopup을 넣어 "이것을 누르면 또 다른 창이 있습니다" 그리고 "이 창은 닫혀있습니다/열려있습니다" 하며 알 수 있게 했습니다.

https://user-images.githubusercontent.com/72232928/165316785-53f0bbc1-d7a2-49b7-a034-528b85a76cec.mov

마지막으로 mobile menu에서 tab을 계속 누르면은 focus가 다시 위로 올라가게 하였습니다. (shift + tab을 누르면 반대 방향으로 갑니다.)

https://user-images.githubusercontent.com/72232928/165325184-214c3431-2bba-4d8a-a324-95095714cb6c.mov

-------------------------

[이 웹사이트](https://hyungmogu.github.io)에 가시면 제 결과물을 보실 수 있습니다.

관리자님, 이 개선안을 진행해도 괜찮습니까? 부족한 점이 있으면은 고치겠습니다.

관리자님, 시간내어 제 issues를 봐주셔서 고맙습니다.

감사합니다.

**Comment by haksungjang** [comment]
@hyungmogu 님, 

자세한 이슈에 대한 설명과 PR까지 보내주셔서 정말 감사합니다. 
SKT 오픈소스 웹사이트의 개선에 큰 힘이 되고 있습니다. 

감사합니다. :)

**Comment by hyungmogu** [comment]
관리자님, 저야말로 감사합니다.
제 자그마한 기여가 관리자님의 그리고 회사의 힘이 될 수 있어 날아갈 듯한 기분입니다.
관리자님, 이렇게 좋은 뉴스 주셔서 고맙습니다.
관리자님, 감사합니다!
