### ISSUE TITLE
sktelecom.github.io의 updated css 미반영 문제 해결

### ISSUE THREAD

**Issue by hyungmogu** [sktelecom/sktelecom.github.io#54]
안녕하새요.

github gh-pages 관련 issue를 올립니다.

/assets/scss 폴더 안에 있는 _nav.scss파일의 콘텐츠를 바꾸고 github에 commit을 했더니 change가 gh-pages에 반영되지 않습니다.

![image](https://user-images.githubusercontent.com/6856382/165655222-2cc54b54-f07d-4602-9e23-56758d2272e1.png)

참고: [_nav.scss 수정 전](https://github.com/sktelecom/sktelecom.github.io/blob/master/assets/scss/_nav.scss), [_nav.scss 수정 후](https://github.com/hyungmogu/hyungmogu.github.io/blob/92ea41996814ea1059d6f45ddfb5534375514c8b/assets/scss/_nav.scss), [수정 후 compiled 된 파일](https://github.com/hyungmogu/hyungmogu.github.io/blob/a8c9a10aa48d8e87fe3e86a8622b24f754211946/scss/main.min.9ffeee081134e12243bebc919d1a0e498b6897457e5c8f756d67b785416cb6bf.css)

(/assets/scss 안에 있는 _nav.scss 파일을 변경하고 이것을 commit하면은 problem을 replicate 할 수 있습니다.)

[온라인](https://discourse.gohugo.io/t/postcss-error-with-snap-install/36136/2)에서는 이 원인이 postcss, postcss-cli 그리고 autoprefixer를 설치하지 않아서 나오는 문제이기에 설치하면은 해결할 수 있다고 나와 있습니다.

그리고 /themes/layouts/partials/head-css.html 안에 있는 코드를 /layouts/partials/head-css.html로
복사하고 아래에 있는 내용으로 변경한 다음 `git commit`를 실행하면 github action 안에 에러 "PostCSS가 설치되어 있지 않습니다"를 확인했습니다.

```
<!-- /layouts/partials/head-css.html -->

{{ $scssMain := "scss/main.scss"}}
{{ if .Site.IsServer }}
{{/* Note the missing postCSS. This makes it snappier to develop in Chrome, but makes it look sub-optimal in other browsers. */}}
{{ $css := resources.Get $scssMain | toCSS (dict "enableSourceMap" true) }}
<link href="{{ $css.RelPermalink }}" rel="stylesheet">
{{ else }}
{{ $css := resources.Get $scssMain | toCSS (dict "enableSourceMap" false) | postCSS | minify }}
<link rel="preload" href="{{ $css.RelPermalink }}" as="style">
<link href="{{ $css.RelPermalink }}" rel="stylesheet" integrity="{{ $css.Data.integrity }}">
{{ end }}
```

![image](https://user-images.githubusercontent.com/6856382/165655296-3a767a48-046c-4057-9f2b-9842fa2cab62.png)

local repository에 다음의  package.json을 include하고 `git commit`을 실행한 결과 scss change가 문제없이 반영됩니다.

```
{
  "name": "sktelecom.github.io",
  "version": "1.0.0",
  "description": "Welcome to the GitHub repository for open source portal website at SK telecom. The portal are hosted at http://sktelecom.github.io/.",
  "main": "index.js",
  "directories": {
    "doc": "docs"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "autoprefixer": "^10.4.5",
    "postcss": "^8.4.12",
    "postcss-cli": "^9.1.0"
  }
}
```

관리자님, 현재의 package-lock.json은 아무 관련이 없는데 이 파일을 remove 해도 괜찮습니까?

![image](https://user-images.githubusercontent.com/6856382/165655348-01b0675c-a811-413b-9903-ff23d5cc02bf.png)

관리자님, 시간내어 제 issue를 읽어주셔서 고맙습니다.

감사합니다.

**Comment by haksungjang** [comment]
@hyungmogu 님, 

Issue 생성과 PR 감사합니다!
Merge하였습니다. 

Thank you! :)
