### ISSUE TITLE
sktelecom.github.io layout 개선

### ISSUE THREAD

**Issue by hyungmogu** [sktelecom/sktelecom.github.io#56]
안녕하세요 @haksungjang님,

꽃이 많이 핀 요즘 가족과 함께 좋은 시간 보낼 수 있도록 따뜻한 산들바람이 가득합니다.

관리자님, 이번엔 SK Telecom에 오시는 모든 분들께 보다 좋은 user experience를 갖기 위한 layout 관련 개선안 issue를 올립니다.

처음에 footer를 개선하며 아, footer를 먼저 하기 전에 이것을 먼저 해야겠구나 생각이 들었습니다.

제 개선안의 핵심은 "깔끔히 mobile view는 mobile에 맞게, tablet view는 tablet에 맞게, desktop view는 desktop에 맞게"입니다.

---------------------

1. 첫 번째로 mobile, tablet, 그리고 desktop의 공통적인 문제인 footer의 white space 문제를 해결했습니다.

![correction-1](https://user-images.githubusercontent.com/72232928/167268330-a5fd45d2-a849-43e4-9262-95c82dd0ff39.png)

[Commit 링크](https://github.com/hyungmogu/sktelecom.github.io/commit/bf128b683c96e4b1829f006ef5cbf666eb28f8d8)

---------------------

2. 두 번째로 new footer를 implement 했을 때 양 옆이 하얗게 보이는 문제를 고쳤습니다.

![correction-2](https://user-images.githubusercontent.com/72232928/167280310-4b22fa38-98ef-493a-9533-e494bad2c042.png)

[Commit 링크](https://github.com/hyungmogu/sktelecom.github.io/commit/932001fb1987f43ec7e9883626e4693f220ad059)

---------------------

3. 세 번째로 두 번째 문제를 해결했을 때 [blog](https://sktelecom.github.io/blog/), [projects](https://sktelecom.github.io/project/), [guide](https://sktelecom.github.io/guide/), [compliance](https://sktelecom.github.io/compliance/)에서 양 옆의 부분이 browser width 밖으로 나가는 문제를 바로잡았습니다.

![correction-3](https://user-images.githubusercontent.com/72232928/167280282-a06d3712-dc8e-4aeb-b347-5a95f61b2fe4.png)

[Commit 링크](https://github.com/hyungmogu/sktelecom.github.io/commit/cb546d32cb167235c24d4fd275b5737f5d850cdc)

---------------------

4. 네 번째로 [blog](https://sktelecom.github.io/blog/), [projects](https://sktelecom.github.io/project/), [guide](https://sktelecom.github.io/guide/), [compliance](https://sktelecom.github.io/compliance/) 안에 있는 mobile side bar menu를 보다 쉽게 접근 할 수 있게 button의 width를 넓히고 색깔을 회색으로 바꾸었습니다.

**수정 후**

https://user-images.githubusercontent.com/72232928/167300538-873ce6bd-4ebe-467e-b0c3-0fb7be844aac.mov

[Commit 링크](https://github.com/hyungmogu/sktelecom.github.io/commit/27d43a4cbef4ab9d2e8dbdc9963c61e188f954e2)

---------------------

5. 다섯 번째로 home page banner의 text 하고 button이 위로 쏠린 문제를 해결했습니다.

![correction-5](https://user-images.githubusercontent.com/72232928/167303001-c3813242-924d-458b-8470-b0cc005b6657.png)

[Commit 링크](https://github.com/hyungmogu/sktelecom.github.io/commit/c4038df81e489d2998057186fbd6be1c27fce2b0)

---------------------

6. 여섯 번째로 home page banner의 다음 버튼을 누르면 완벽하게 target section으로 갈 수 있게 해결했습니다.

**수정 전**

https://user-images.githubusercontent.com/72232928/167315642-0f8166ce-7029-443f-bb67-bee12463c94d.mov

**수정 후**

https://user-images.githubusercontent.com/72232928/167315649-2df6f07d-cd10-46f7-97f0-e702d5e4e1ec.mov

[Commit 링크](https://github.com/hyungmogu/sktelecom.github.io/commit/46a7b99d319f3f6d0ad39ee0c0fd7d7d5c861c62)

---------------------

7. 일곱 번째로 home page의 콘텐츠가 mobile, tablet, 그리고 desktop view에서 깔끔하게 보이도록 layout을 tune 했습니다.

**수정 전**

https://user-images.githubusercontent.com/72232928/167317855-cf869aa8-d1b4-46f9-9bc6-a2f49877224d.mov

**수정 후**

https://user-images.githubusercontent.com/72232928/167317620-ce651669-ff4a-4e94-b229-080fa3c9b2eb.mov

[Commit 링크](https://github.com/hyungmogu/sktelecom.github.io/commit/1df8df422bf48e0ccee17e9a30fd3d56bf1acfca)

---------------------

8. 여덟 번째로 오른쪽 sidebar에 있는 푸른색 hover color를 sk telecom theme에 맞게 오렌지 색으로 바꾸었습니다.

![correction-7](https://user-images.githubusercontent.com/72232928/167273982-120b629c-0598-490c-8301-0d40574fad71.png)

[Commit 링크](https://github.com/hyungmogu/sktelecom.github.io/commit/3dad6ffc4081dec02a9dd98a14134e8b78ea5c3c)

---------------------

9. 아홉 번째로 tablet으로 [blog](https://sktelecom.github.io/blog/), [projects](https://sktelecom.github.io/project/), [guide](https://sktelecom.github.io/guide/), [compliance](https://sktelecom.github.io/compliance/)로 들어갔을때 필수적인 부분만 보이게 하여 북적함을 줄이고 읽기 쉽게 했습니다.

![correction-8](https://user-images.githubusercontent.com/72232928/167273560-946c9cf9-b31c-4e21-8ea0-181a31c6b185.png)

[Commit 링크](https://github.com/hyungmogu/sktelecom.github.io/commit/cb4c17347c3740fa164174b162f365e66eeafdcd)

---------------------

이 모든 변경사항들을 이 [링크](https://hyungmogu.github.io)에 가시면은 보실 수 있습니다.

관리자님, 수정해야 할 부분이 있으면 꼭 말씀해 주세요. 제가 수정하겠습니다.

관리자님, 지난주 제게 칭찬을 주셔서 정말 고맙습니다.

감사합니다.

**Comment by haksungjang** [comment]
@hyungmogu 님,

SK텔레콤의 오픈소스 웹사이트의 UI개선에 적극적으로 기여해주셔서 감사합니다. 
세세한 부분까지도 관심을 갖고 개선해 주셔서 깊은 감동을 받았습니다. 

감사합니다! :)

**Comment by hyungmogu** [comment]
@haksungjang님,

sk telecom을 위해 조그맣게라도 기여할 수 있어 영광입니다. 
제게 개선할 수 있는 기회를 주시고 칭찬을 주셔서 정말 고맙습니다.

감사합니다.
