### ISSUE TITLE
sktelecom.github.io 검색창 길이 개선 (모든 브라우져)

### ISSUE THREAD

**Issue by hyungmogu** [sktelecom/sktelecom.github.io#61]
안녕하세요 @haksungjang님,

파이어폭스 하고 사파리 브라우져에서 navigation안에 있는 검색창이 보다 크게 나와있어 chrome 브라우져 사이즈와 동일하게 보이도록 수정해서 올립니다.

-------------
**수정 전**

![navigation-bar-before](https://user-images.githubusercontent.com/72232928/168511601-8ce00789-0644-44e2-bdfc-4eacceb40670.png)

[다른 브라우져들 스크린샷으로 보기](https://links.lambdatest.com/6T77QVOAFLAR2LPEUMVUVO4ZLKJOX796GDPVH09G2K3JCAXIYV455MDBCY4LDO0T)

-------------
**수정 후**

![navigation-after](https://user-images.githubusercontent.com/72232928/168512826-b037dacd-6761-4d31-bb38-cc7ec78e69ad.png)

[다른 브라우져들 스크린샷으로 보기](https://links.lambdatest.com/9DQNCV31P0KNIHMYL1P8UQ88Y6FSOSDOLMO8R3PFHQVEM4AFNSOABVCDILOID2WB)

-------------

그리고 관리자님, 제 부족으로 지난 개선안에서 못한 scss 파일 안에 있는 bracket들을 tighten 해서 함께 올립니다.

관리자님, 소중한 시간내어 제 issue를 봐주셔서 고맙습니다.

감사합니다.

**Comment by haksungjang** [comment]
@hyungmogu 님, 
적극적인 기여에 항상 감사합니다. 

LambdaTest란 사이트도 처음 알게 되었네요. 
유용한 정보와 활발한 활동에 다시 한번 감사 드립니다. :)

**Comment by hyungmogu** [comment]
@haksungjang님, 
제가 더 고맙습니다 :D.

관리자님 덕분에 새로운 것도 도전하고 기여할 수 있습니다.
SK Telecom을 위해 조그맣게라도 기여할 수 있어 기쁘고 행복하고 즐겁습니다 :D!

관리자님, 제게 이 기회를 주셔서 정말 고맙습니다.

감사합니다.
