### ISSUE TITLE
sktelecom.github.io pull request check 에러 개선

### ISSUE THREAD

**Issue by hyungmogu** [sktelecom/sktelecom.github.io#65]
안녕하세요 @haksungjang님,

Pull request를 하는데 build github pages / build (pull_request) 부분에서 에러가 나타나 이에 관한 개선안을 올립니다.

![image](https://user-images.githubusercontent.com/72232928/169663734-709f8937-ce98-4eb3-bdda-67b8ec1f93e1.png)

이 에러의 원인은 hugo v0.99 업데이트에 있습니다.

![cause-1](https://user-images.githubusercontent.com/72232928/169670851-853b8b62-5a9d-4535-819c-a454a3dffd28.png)

hugo가 v0.99에서 `hugo --minify`에서 나오는 에러를 더 이상 ignore 하지 않기 때문입니다 ([링크](https://github.com/gohugoio/hugo/issues/9884#issue-1233699003)).

지난 pull request에서는 hugo v0.98를 사용했기 때문에 문제가 나와도 에러가 나오지 않았습니다.

![cause-2](https://user-images.githubusercontent.com/72232928/169671047-0c2b7001-8907-4f40-8652-2a9e0848715f.png)

postcss-cli missing 문제를 해결하기 위해 [이 solution](https://github.com/sktelecom/sktelecom.github.io/issues/54)을 참고해서 업데이트를 했습니다.

그 결과, build github pages / build (pull_request)에서 더 이상 conflict이 일어나지 않고 있습니다 ([링크](https://github.com/hyungmogu/sktelecom-hugo-v0.99-merge-error-cause-analysis/pull/2)).

![result](https://user-images.githubusercontent.com/72232928/169672769-3e3b1374-1592-4da7-9057-4b46532ede74.png)

관리자님, 부디 좋은 하루 보내세요.

감사합니다.

**Comment by hyungmogu** [comment]
@haksungjang 님, 늦어서 죄송합니다! 마지막에 master branch에서 이상한 기운이 감지되어 수정하는데 시간이 오래 결렸습니다.

관리자님에게 평가이하 work를 보내고 싶지 않았습니다.

죄송합니다!

**Comment by haksungjang** [comment]
@hyungmogu 님, 
확인하였습니다. 자세한 설명 감사합니다! :)
