### ISSUE TITLE
sktelecom.github.io의 blog 페이지 오른쪽 sidebar layout 개선

### ISSUE THREAD

**Issue by hyungmogu** [sktelecom/sktelecom.github.io#67]
안녕하세요 @haksungjang님,

sktelecom.github.io의 보다 나은 웹사이트를 위해 sidebar layout 개선 관련 issue를 올립니다.

여기에 문제는 blog page 오른쪽에 있는 sidebar에 margin이 있어 보다 좁아 보입니다.

![enhancement-problem-before](https://user-images.githubusercontent.com/6856382/170406561-18d49984-8a61-40e3-a542-ceba1d27f8c1.png)

그리하여 이 부분을 다음과 같이 정리했습니다.

![enhancement-problem-after](https://user-images.githubusercontent.com/6856382/170406577-c7261aed-c118-41c6-a770-a7b3f44d3f71.png)

[이 웹사이트](https://hyungmogu.github.io/sktelecom-hugo-enhance-side-bar-20220525/blog/2022/20220403_innersource/)로 가시면 결과물을 보실 수 있습니다.

관리자님, 만약 이 부분에 대해서 추가적으로 수정해야 할 곳이 있으면 꼭 말씀해 주세요. 수정하겠습니다.

관리자님, 부디 좋은 하루 보내세요.

감사합니다.

**Comment by haksungjang** [comment]
@hyungmogu 님, 안녕하세요. 

보내주신 PR을 merge하였습니다. 
세세한 부분까지 신경써서 개선해주셔서 감사합니다. 
(Review가 늦어져서 죄송합니다.) 

감사합니다! :)

**Comment by hyungmogu** [comment]
안녕하세요 @haksungjang님,

괜찮습니다 :).

관리자님, 제 issue를 읽어주시고 pull request를 받아주셔서 고맙습니다. 

감사합니다.
